version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      - MONGO_URL=mongodb://db:27017/mydb
  db:
    image: mongo:6
    restart: always
    volumes:
      - dbdata:/data/db
    networks:
      - mynetwork
volumes:
  dbdata:
networks:
  mynetwork:
    driver: bridge
